import enum


class TransferPurposeSubTransferPurpose(enum.Enum):
    INTERPRETATION_SERVICE = "INTERPRETATION_SERVICE"
    TRANSLATION_SERVICE = "TRANSLATION_SERVICE"
    HUMAN_RESOURCE_SERVICE = "HUMAN_RESOURCE_SERVICE"
    ESTATE_AGENCY_SERVICE = "ESTATE_AGENCY_SERVICE"
    SOFTWARE_DEVELOPMENT_SERVICE = "SOFTWARE_DEVELOPMENT_SERVICE"
    WEB_DESIGN_OR_DEVELOPMENT_SERVICE = "WEB_DESIGN_OR_DEVELOPMENT_SERVICE"
    DRAFTING_LEGAL_SERVICE = "DRAFTING_LEGAL_SERVICE"
    LEGAL_RELATED_CERTIFICATION_SERVICE = "LEGAL_RELATED_CERTIFICATION_SERVICE"
    ACCOUNTING_SERVICE = "ACCOUNTING_SERVICE"
    TAX_SERVICE = "TAX_SERVICE"
    ARCHITECTURAL_DECORATION_DESIGN_SERVICE = "ARCHITECTURAL_DECORATION_DESIGN_SERVICE"
    ADVERTISING_SERVICE = "ADVERTISING_SERVICE"
    MARKET_RESEARCH_SERVICE = "MARKET_RESEARCH_SERVICE"
    EXHIBITION_BOOTH_SERVICE = "EXHIBITION_BOOTH_SERVICE"


class SourceOfFunds(enum.Enum):
    SALARY = "verification.source.of.funds.salary"
    INVESTMENTS = "verification.source.of.funds.investment"
    INHERITANCE = "verification.source.of.funds.inheritance"
    LOAN = "verification.source.of.funds.loan"
    OTHER = "verification.source.of.funds.other"
